// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgahcgvfhjrdjxfqxuvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnYWhjZ3ZmaGpyZGp4ZnF4dXZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NDUzNTMsImV4cCI6MjA1MzIyMTM1M30.Y4a1t-yUI976Wkq4e3AH__X7662fTo0szJy_S74hd30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);